# Generated by Django 6.0.5 on 2026-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Member', 'Member')], default='Member', max_length=50),
        ),
    ]
